### ISSUE TITLE
MD5 is missing with -ignore-checksums raising error

### ISSUE THREAD

**Issue by igor-raits** [aptly-dev/aptly#151]
```
$ aptly mirror -ignore-checksums -ignore-signatures update mirantis
```

prints

```
ERROR: unable to update: unable to compute pool location for filename curl_7.22.0-3ubuntu4.8_amd64.deb, MD5 is missing
```

and exit with err_code. I think when we ignoring checksums we should ignore missing checksums

**Comment by linuxluser** [comment]
This bug has broken the ability for me to use google-cloud-sdk ([example Packages file with missing MD5sum filed](https://packages.cloud.google.com/apt/dists/cloud-sdk-jessie/main/binary-amd64/Packages)).

Given that MD5sum is no longer required by the repository format spec (in fact, it's discouraged), I believe the responsibility should fall on aptly to conform to the spec. Specifically, instead of requiring MD5, require SHA256. Here's what [the spec](https://wiki.debian.org/RepositoryFormat#Size.2C_MD5sum.2C_SHA1.2C_SHA256.2C_SHA512) reads:

> At least one field providing a SHA2 hash shall be provided. Providing SHA256 is highly recommended ...
> Clients may not use the MD5Sum and SHA1 fields for security purposes, and must require a SHA256 or a SHA512 field.

If I'm reading this correctly, in this context, aptly would be considered a 'client' and thus should not use MD5sum or SHA1. It also means that even if there are repositories that only provide md5sum field for some reason (old, etc), Apt clients ought not use them anyway.
