### ISSUE TITLE
feature request: read filters from file

### ISSUE THREAD

**Issue by smira** [aptly-dev/aptly#157]
Filter line could be longer than command line limit. 

Probably, support format of multiple liens and convert it into 'line1 | line2 | ...' automatically.

**Comment by flamableconcrete** [comment]
Any progress on this? This would be super useful!

**Comment by tirolerstefan** [comment]
When switching from reprepro (with mirror and filterlist file), this feature would really be important.

Filterlist in reprepro looks like this:

`accountsservice install
acl install
acpi-support purge
acpid install
adduser install`

**Comment by 5hir0kur0** [comment]
Reading from a file is now possible since #1411 was merged.

Currently, newlines are just treated as whitespace, but what you can already do is take your newline-separated package file and add `|` in front of all newlines (except for the last), e.g.:

```
vim-common |
bash |
libc6
```

You can then use it as a filter with `aptly mirror create -filter='@/path/to/packagelist' ...`.

**Comment by neolynx** [comment]
a list of package files can be converted with `sed -e '$ ! s/$/ |/'` to automatically add the `|` except on the last line.

**Comment by neolynx** [comment]
closing as this is now possible
