### ISSUE TITLE
Support multiple components in local repositories

### ISSUE THREAD

**Issue by sobczyk** [aptly-dev/aptly#498]
aptly supports components only at publish, but supporting at local repo would alleviate a lot of user confusion, and simplify some tasks (mostly mirroring, but also multi component repos)

> aptly repo create
> aptly mirror create

Should support multiple components, that propagate to the publish phase

Some commands would need to be updated like aptly repo move (ie. preserve component by default, specify if want other)

## Context
usually multiple components do not have common packages, as they create one whole repository,
so searching package in a single repo benefits.
Creating mirrors of upstream debian or ubuntu means a lot of commands, I know this can be automatedm,
but still "xenial" is better than "xenial_main" "xenial_universe" ets and then making sure it's published properly

Ideal flow would be `aptly mirror create xenial http://address.of.repo xenial` and have it autodiscover all settings, optionally passing architectures and components,
then `aptly snapshot create xenial from mirror xeial && aptly publish snapshot xenial` and have the same components as in upsream

## Possible Implementation
This would most probably break compatibility so it'd need major version change, and probably require some tooling to convert current data

**Comment by sobczyk** [comment]
this could also be a milestone towards
"mirror repositories "as-is" (without resigning with user's key) (+)"
since an additional `aptly publish mirror <name>` would be sufficient

**Comment by smira** [comment]
At some point in time (several years ago) I decided to avoid multiple components in single mirror/snapshot/repo, as it seems to complicate commands a lot (like you mentioned). That made multi-component publishing real nightmare. I wonder if we could try to implement component as "tag" which is attached to the package when package is part of snapshot. Internally, as it's all about packageRefList, that means that packageRefList contains list of package references + list of tags for each package. That way tags would stick to the package, so that it's copied/moved around, tag would stay (or if say snapshot is created from the mirror). During publish phase we can auto-detect list of components and publish them accordingly.

**Comment by smira** [comment]
To say it different way, if we want to have multi-component snapshot (for example, or repo, or mirror), we have two options:

1. Add several PackageRefLists, one for each component
2. In single PackageRefList, tag each package with component

I like (2) so far more, as it's probably less changes and it means that still single repo/snapshot/mirror doesn't have duplicate packages.

**Comment by sobczyk** [comment]
Number 2 sound better, but it doesn't allow for an empty component, at least I can't imagine how it can be implemented

**Comment by smira** [comment]
Yep, empty component would be tricky unless you force list of components during publish? (So that any component without packages would be empty?)

**Comment by sobczyk** [comment]
What if there is more components at some point? it'd be nice if the published repo expanded/shrinked when publishing. ie. automatically adding more components, removing, same with arch.
I think it's impossible right now.

Another possibility is an empty/virtual package with a tag that'd force a component.
