### ISSUE TITLE
aptly snapshot filter - dependency resolution issue

### ISSUE THREAD

**Issue by ilendir** [aptly-dev/aptly#562]
I use aptly snapshot filter to filter packages and later install a custom package from a small published repo with all the dependencies from the custom package. This, however, leads to issues that the installation sometimes fails because there is a needed package missing.

## Detailed Description
 I have a package ("my_package.deb") that has the following dependencies (actually more, but these should be the relevant ones):

    xserver-xorg-video-intel, xserver-xorg-video-vesa, xserver-xorg-video-fbdev,
    xorg, nodm, xvfb,

And I have a huge merged_snapshot that contains all packages from a Ubuntu 16.04 aptly mirror.
Then, I use the merged ubuntu snapshot to filter according to the dependencies of my package:

    aptly snapshot filter -with-deps=true -dep-follow-all-variants=true $MERGED_SNAP $FILTERED_SNAP "my_package"

Now, I install a minimal ubuntu server installation and during that installation (via preseed) I want to install my_package. That usually works like a charm, but sometimes, aptly seems to have forgotten a transitive dependency. Namely **xserver-xorg-input-wacom**.

My installation fails with the error message that apt cannot install my_package, because **xorg** has unmet dependencies. If I try to install **xorg** per hand, I get the next error that **xorg** has unmet dependencies  (**xserver-xorg**) and there is a impossible situation and apt cannot resolve that issue. 

When I try to install **xserver-xorg** I get the error that it has has unmet dependencies (**xserver-xorg-core**). However, If I try to install **xserver-xorg-core** per hand, it somehow works.....after that I can install **xserver-xorg** per hand, and so on.

## Context

I do realize that I can just add **xserver-xorg-input-wacom** to my dependencies and be done with that issue, but this seems to be a bug that I spuriously cannot install xorg because there is some package missing. And I assume that might happen sometimes in the future with other packages as well as the nature of package filtering seems to be unstable (see comments here: https://www.aptly.info/doc/aptly/snapshot/filter/ ).

As this is an issue that only happens sometimes, I'm not really sure how to reproduce this issue properly. 

## Your Environment

Ubuntu 16.04, aptly version: 0.9.6

Thanks for your great work with aptly!

**Comment by flamableconcrete** [comment]
@ilendir: did you ever get this problem solved? Or did you just move on?

**Comment by ilendir** [comment]
@flamableconcrete Nope, the bug still remains. As I wrote in "Context" I could add the missing package to the dependencies of my package and be done with it and that's exactly what I did. The problem in aptly, however, still seems to remain.

**Comment by sehe** [comment]
I have similar issues. I have three mirrors of 18.04 repos (main, universe, multiverse) all filtered on a package list (-filter-with-deps).

I simply merge snapshots of all three into my staging snapshot (adding a small number of my own application packages).

When installing my application from the resultant published repo, I get missing packages.

The problem is that some dependencies aren't recursed because they're not within the same component as the one being mirrored. These dependencies can be buried really deep inside the dependencies of other packages, and even tracing back to the missing package can be tedious. 

There should really be a way to allow recursively inspecting dependencies from other components (so a `dependencyFollowAllComponents` similar to the existing `dependencyFollowAllVariants`)
