### ISSUE TITLE
Gpg 2.1 compatiblity

### ISSUE THREAD

**Issue by michael-todorovic** [aptly-dev/aptly#657]
Hello,
I'm on Debian Stretch (gpg 2.1). I generated my gpg key so I have a .gnupg/pubring.kbx instead of .gnupg/pubring.gpg and .gnupg/secring.gpg. The gpg provider doesn't work but I can't get the internal provider to work.
`host:~$ aptly publish repo -batch -gpg-key=<blah> -passphrase-file="/data/aptly/.DoNotRemoveMandatoryForAptly" -gpg-provider=internal <name> <prefix>
opengpg: failure opening keyring '/data/aptly/.gnupg/pubring.gpg': open /data/aptly/.gnupg/pubring.gpg: no such file or directory
opengpg: failure opening keyring '/data/aptly/.gnupg/secring.gpg': open /data/aptly/.gnupg/secring.gpg: no such file or directory
ERROR: unable to initialize GPG signer: couldn't find key for key reference <blah>`

I tried to specify -secret-keyring with the kbx and it didn't work either:
`ERROR: unable to initialize GPG signer: error load secret keyring: openpgp: invalid data: tag byte does not have MSB set`

Am I doing something wrong or does it need a fix (I may submit a PR then)?
Thanks!

**Comment by smira** [comment]
aptly doesn't support gpg 2.1 both when using external `gpg` program & when using internal OpenPGP implementation (which doesn't support new keyring format).

**Comment by mischelebuha** [comment]
I have the same problem, aptly should support gpg 2.1 as soon as possible. Because, finally, this is since debian stretch the common version of gpg.

**Comment by pszynk** [comment]
For me gpg 2.1 works, but I've had a problem with `-passphrase` option (it asked for password anyway).   This answer helped me - [superuser.com](https://unix.stackexchange.com/a/415064/277109).

**Comment by brucepc** [comment]
I have the same problem with `gpg 2.1.18` and `libgcrypt 1.7.6-beta` the option `-passphrase` don't work as planned, with or without `-batch[=true]`.

**Comment by apachelogger** [comment]
Some quick notes for future reference:

I think the `gpg2` provider probably just needs some testing to figure out the necessary parameters (most definitely `--passphrase-file` must be combined with `--batch`. I am not entirely sure how that will play with potential pinentry configuration on the agent side though. Certainly needs some investigation.

As for the builtin provider in general: gpg2's main change over gpg1 is that none of the clients ever touch the keys directly. Instead, they talk to the gpg-agent and the agent does the work for them (https://www.gnupg.org/documentation/manuals/gnupg/Agent-Protocol.html). My google skills seem to be failing me hard on this one. I only glanced at it, but https://github.com/prep/gpg seems like a viable solution to talk to the agent. Alternatively we'd have to implement our own client, or discontinue the builtin provider for gpg2.

This also has some additional implications for the system tests. We'll need to start our own agent so it uses our testing keyrings. From what I understand this should be easy enough as the agent the client talks to is controlled by environment variables (`GPG_AGENT_INFO` specifically).

The gnupg Signer and Verifier seem to implement a whole bunch of functions which will likely not be translatable to gpg2 (e.g. setting a different keyring isn't a thing with the agent system). From what I've seen these features are only used internally though, so it may not be that big a deal.

**Comment by absltkaos** [comment]
So along these lines... I also had gpg 2.1 working. I wrote a small script that would preseed the gpg passphrase for me in the agent, so that the `gpg` binary can work without prompting. Ended up having to symlink `/usr/bin/gpg` to `/usr/bin/gpg2`. 

All was working well until just recently (with the 1.3.0 update) when I observed the following bizarre behavior:

When running `aptly` locally, to publish a repository I get the following:
```
repo@repo:~$ aptly publish update dev                  
panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH [recovered]
        panic: Couldn't find a suitable gpg executable. Make sure gnupg1 is available as either gpg or gpg1 in $PATH

goroutine 1 [running]:
github.com/aptly-dev/aptly/cmd.Run.func1(0xc4206ebf50)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:17 +0x131
panic(0xbe4aa0, 0xc4201622a0)
        /usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:491 +0x283
github.com/aptly-dev/aptly/pgp.NewGpgSigner(0xc4200fe0c0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/pgp/gnupg.go:121 +0xba
github.com/aptly-dev/aptly/context.(*AptlyContext).GetSigner(0xc4200fe0c0, 0x0, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/context/context.go:403 +0xd7
github.com/aptly-dev/aptly/cmd.getSigner(0xc420293500, 0xc420293500, 0x4, 0x1, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/publish.go:14 +0x7e
github.com/aptly-dev/aptly/cmd.aptlyPublishUpdate(0xc42028f200, 0xc4202196a0, 0x1, 0x2, 0x1152680, 0xc4201bd620)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/publish_update.go:47 +0x3dd
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc42028f200, 0xc4202196a0, 0x1, 0x2, 0xc42028be01, 0xc42028be18)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:305 +0x2a7
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc42028f440, 0xc420219690, 0x2, 0x3, 0xc420000101, 0xd0f3c0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/vendor/github.com/smira/commander.(*Command).Dispatch(0xc42028fc20, 0xc420219680, 0x3, 0x4, 0xc420293500, 0xc420219680)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/vendor/github.com/smira/commander/commands.go:283 +0x151
github.com/aptly-dev/aptly/cmd.Run(0xc42028fc20, 0xc42000e090, 0x3, 0x3, 0xc420214101, 0x0)
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/cmd/run.go:41 +0x12a
main.main()
        /Users/smira/Documents/go/src/github.com/aptly-dev/aptly/main.go:24 +0x151
```

**Comment by smira** [comment]
This is related to #741

**Comment by jdelic** [comment]
I'd like to add some notes on gpg2 behavior.

1. GnuPG 2.1+ seems to start gpg-agent if one isn't running in the current context. So I don't think that aptly needs to talk to gpg-agent directly. As far as I know, Enigmail (a popular Thunderbird plug-in for supporting GPG-encrypted email) also just calls the `gpg` executable and parses its output. I believe setting `GNUPGHOME` to the keyring should be enough. Just in general, where I was previously using GnuPG 1.x with different keyrings in a single folder, specifying `--keyring, --secret-keyring and --trustdb`, nowadays I have one keyring per folder and specify `--homedir`, which seems to work fine.

2. I had GnuPG 2.1 working with aptly as well. As @michael-todorovic correctly wrote, passing the passphrase has become more difficult, but is absolutely possible using the loopback pinentry mode. If gnupg had better documentation instead of the cesspool of undocumented behaviors and inconsistent command-line switches, this would be much more obvious.

**How to enable GnuPG 2.1+ with passphrases from other processes and aptly in general (before aptly 1.3.0 broke this)**

1. `--secret-keyring` is meaningless in GnuPG 2.1+. The right thing to do is to set `export GNUPGHOME=/my/aptly/keyring` in aptly's environment and have a version 2 keyring there.

2. in `/my/aptly/keyring` create the following configuration files:

```
gpg.conf:
pinentry-mode loopback
```

```
gpg-agent.conf:
allow-loopback-pinentry
```

3. Either use `-passphrase-file` or write the passphrase to `gpg`'s `stdin`. Like @absltkaos I'm storing the passphrase in Hashicorp Vault. I load it via my own [vaultwrapper.py](https://github.com/gopythongo/gopythongo/blob/60015ac11de78a1b97997b23ad04cd45b422b89f/src/py/gopythongo/vaultwrapper.py) script and pass `-passphrase-file /dev/stdin` to aptly.

Unfortunately the above configuration options in `gpg.conf` and `gpg-agent.conf` are incompatible with GnuPG 1.x. So until #743 lands, all of my Debian deployments with aptly are broken now because I can't easily downgrade my signing keyrings to gpg1 on my build servers without breaking other software that relies on GnuPG 2.x with loopback pinentry :(. So now I have to duplicate my keyrings until this is fixed. I hope #743 can land soon.

**Comment by smira** [comment]
Thanks for detailed analysis, I'm going to merge #743 which should soon be published as nightly build while I'm working on gpg2 support and tests.

**Comment by smira** [comment]
#743 is included into nightly build `aptly_1.3.0+10+g90e446e`

**Comment by absltkaos** [comment]
@jdelic FYI, You can avoid pinentry and touching `gpg.conf` if you do the following as well:

Set `allow-preset-passphrase` in `gpg-agent.conf`

Then look up what the keygrip of you key is with:
```
gpg2 --with-keygrip -K [keyid]
```
(Add a `--with-colons` if you want to parse the output easier)

Then just call `gpg-preset-passphrase` and send it the passphrase on stdin (On Ubuntu that executable is found here: `/usr/lib/gnupg2/gpg-preset-passphrase`, Suse and I believe CentOS is here `/usr/lib64/gpg-preset-passphrase`)
```
echo 'passphrase' | gpg-preset-passphrase --preset [keygrip]
```

**Comment by smira** [comment]
Should be fixed with #779

**Comment by pityonline** [comment]
I migrated from CentOS 7 to Debian Stretch with `~/.aptly.conf`, yes, the GPG keys are also migrated, but ran into the same error.

```
opengpg: failure opening keyring '/home/user/.gnupg/pubring.gpg': open /home/user/.gnupg/pubring.gpg: no such file or directory
opengpg: failure opening keyring '/home/user/.gnupg/secring.gpg': open /home/user/.gnupg/secring.gpg: no such file or directory
ERROR: unable to initialize GPG signer: looks like there are no keys in gpg, please create one (official manual: http://www.gnupg.org/gph/en/manual.html)
```

CentOS 7:
aptly: 1.3.0+64+ge2d6a53d
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3

Debian Stretch:
aptly: 1.4.0
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta

What I changed is just one line in `~/.aptly.conf`, and it's solved.

```
"gpgProvider": "internal",
```

to

```
"gpgProvider": "gpg2",
```

**Comment by itayporezky** [comment]
If someone still has issues,
I found this [comment](https://github.com/aptly-dev/aptly/issues/907#issuecomment-637366088)
Importing using `gpg1` and not gpg or gpg2

Worked for me

**Comment by Genda1ph** [comment]
Just checked on Debian Bookworm and @jdelic's advice worked.

You need to use `gpg2`, specify `gpg2` in `aptly.conf` and pass `-passphrase-file` pointing to file with keyring passphrase when publishing.
