### ISSUE TITLE
unable to launch API unsing NFS share as root dir

### ISSUE THREAD

**Issue by opopops** [aptly-dev/aptly#708]
**aptly version: 1.2.0**

I'm trying to launch API by exec this command with user 'aptly':

```shell
aptly@mirror01:~$ aptly api serve  -listen=':8080' -no-lock
```
and have this error:

```shell
ERROR: '/var/lib/aptly' is inaccessible, check access rights
```
As you can see my root dir is '/var/lib/aptly' and is an NFS endpoint with these mounting options:

```shell
X.X.X.X/volume1/mirror/apt on /var/lib/aptly type nfs (rw,noatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=X.X.X.X,mountvers=3,mountport=892,mountproto=udp,local_lock=all,addr=X.X.X.X)
```
mode is correct on this directory, and is writable for user aptly:

```shell
ls -l /var/lib | grep aptly
drwxr-xr-x  4 aptly   root    4096 Feb 27 13:28 aptly
```
The problem happens only with API, because all cli commands works.

Is there a problem with rootdir checking for the API?

**Comment by smira** [comment]
First of all, I would strongly recommend not to place aptly directory on any kind of network filesystem. 

The error comes from https://github.com/smira/aptly/blob/master/utils/utils.go#L19-L21

`access(2)` syscall seems to have pretty limited number of reasons for the failure: https://linux.die.net/man/2/access

There are two things which could be refined:

* I think it would be good to print exact error when this check fails
* aptly probably doesn't need write access (need to verify)

**Comment by tuzakey** [comment]
Ubuntu's 4.15 kernel (Bionic/XenialHWE) has changed(fixed) it's handling of NFS ACCESS_DELETE permission and now access.W_OK fails if the directory doesn't have ACCESS_DELETE. This means that aptly on new Ubuntu installs will not work with the aptly rootdir on NFS export roots.

Workarounds could be:
 * downgrade kernel (not ideal)
 * move aptly root dir in to a directory on the nfs share ~ nfs-server:/myexport/aptlydir instead of nfs-server:/exported-aptly-root (trivial)
 * modify aptly permission checks (this issue)

As Andrey pointed out above keeping the DB on NFS is a bad idea and will cause you problems.
